# Describes the format for available lock services

clear_usercode:
  description: Clear a usercode from lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to clear code from.
      example: 1

get_usercode:
  description: Retrieve a usercode from lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to retrieve a code from.
      example: 1

lock:
  description: Lock all or specified locks.
  fields:
    entity_id:
      description: Name of lock to lock.
      example: "lock.front_door"
    code:
      description: An optional code to lock the lock with.
      example: 1234

open:
  description: Open all or specified locks.
  fields:
    entity_id:
      description: Name of lock to open.
      example: "lock.front_door"
    code:
      description: An optional code to open the lock with.
      example: 1234

set_usercode:
  description: Set a usercode to lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to set the code.
      example: 1
    usercode:
      description: Code to set.
      example: 1234

unlock:
  description: Unlock all or specified locks.
  fields:
    entity_id:
      description: Name of lock to unlock.
      example: "lock.front_door"
    code:
      description: An optional code to unlock the lock with.
      example: 1234
