disable:
  description: Disable configured Pi-hole(s) for an amount of time
  fields:
    duration:
      description: Time that the Pi-hole should be disabled for
      example: "00:00:15"
    name:
      description: "[Optional] When multiple Pi-holes are configured, the name of the one to disable. If omitted, all configured Pi-holes will be disabled."
      example: "Pi-Hole"
enable:
  description: Enable configured Pi-hole(s)
  fields:
    name:
      description: "[Optional] When multiple Pi-holes are configured, the name of the one to enable. If omitted, all configured Pi-holes will be enabled."
      example: "Pi-Hole"
