# Describes the format for available switch services

turn_on:
  description: Turn a switch on.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: "switch.living_room"

turn_off:
  description: Turn a switch off.
  fields:
    entity_id:
      description: Name(s) of entities to turn off.
      example: "switch.living_room"

toggle:
  description: Toggles a switch state.
  fields:
    entity_id:
      description: Name(s) of entities to toggle.
      example: "switch.living_room"
