# Describes the format for available vacuum services

turn_on:
  description: Start a new cleaning task.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

turn_off:
  description: Stop the current cleaning task and return to home.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

stop:
  description: Stop the current cleaning task.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

locate:
  description: Locate the vacuum cleaner robot.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

start_pause:
  description: Start, pause, or resume the cleaning task.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

start:
  description: Start or resume the cleaning task.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

pause:
  description: Pause the cleaning task.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

return_to_base:
  description: Tell the vacuum cleaner to return to its dock.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

clean_spot:
  description: Tell the vacuum cleaner to do a spot clean-up.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"

send_command:
  description: Send a raw command to the vacuum cleaner.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"
    command:
      description: Command to execute.
      example: "set_dnd_timer"
    params:
      description: Parameters for the command.
      example: '{ "key": "value" }'

set_fan_speed:
  description: Set the fan speed of the vacuum cleaner.
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.xiaomi_vacuum_cleaner"
    fan_speed:
      description: Platform dependent vacuum cleaner fan speed, with speed steps, like 'medium' or by percentage, between 0 and 100.
      example: "low"
