# Describes the format for available climate services

set_aux_heat:
  description: Turn auxiliary heater on/off for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"
    aux_heat:
      description: New value of axillary heater.
      example: true

set_preset_mode:
  description: Set preset mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"
    preset_mode:
      description: New value of preset mode
      example: "away"

set_temperature:
  description: Set target temperature of climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"
    temperature:
      description: New target temperature for HVAC.
      example: 25
    target_temp_high:
      description: New target high temperature for HVAC.
      example: 26
    target_temp_low:
      description: New target low temperature for HVAC.
      example: 20
    hvac_mode:
      description: HVAC operation mode to set temperature to.
      example: "heat"

set_humidity:
  description: Set target humidity of climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"
    humidity:
      description: New target humidity for climate device.
      example: 60

set_fan_mode:
  description: Set fan operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.nest"
    fan_mode:
      description: New value of fan mode.
      example: On Low

set_hvac_mode:
  description: Set HVAC operation mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.nest"
    hvac_mode:
      description: New value of operation mode.
      example: heat

set_swing_mode:
  description: Set swing operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.nest"
    swing_mode:
      description: New value of swing mode.

turn_on:
  description: Turn climate device on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"

turn_off:
  description: Turn climate device off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: "climate.kitchen"
